apiVersion: v1
kind: Pod
metadata:
  name: sampleseamless
  annotations:
    k8s.v1.cni.cncf.io/networks: seamless-conf
spec:
  containers:
  - name: sampleseamless
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
#  nodeSelector:
#    debug: "true"
